### ISSUE TITLE
revisit api objects

### ISSUE THREAD

**Issue by tfogo** [mlab-lattice/lattice#121]

**Comment by kevindrosendahl** [comment]
includes:

- state vs status
  - potentially add status block to most objects
- move to k8s objects?
  - spec, status, api version would have to be e.g. lattice.mlab.com
  - could potentially leverage this to have systems able to have components that are native k8s objects (much larger discussion to be had)

**Comment by kevindrosendahl** [comment]
status added in https://github.com/mlab-lattice/lattice/pull/223
